import type { Metadata } from "next";
import { StoreProvider } from "@/app/StoreProvider"
import { Poppins, Inter, Nunito_Sans } from "next/font/google";
import "@/app/Globals.scss";
import Header from "@/theme/components/Header";

const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({subsets:["latin"], weight:[ "400", "100", "200", "300", "500", "600", "700", "800", "900"], display:"swap", style:["normal", "italic"]});
const nunitoSans = Nunito_Sans({subsets:["latin"], weight:[ "400", "200", "300", "500", "600"], display:"swap", style:["normal"]});


export const metadata: Metadata = {
  title: "StreamFlix",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
      <StoreProvider>
        <html lang="en">
          <body className={`${ inter.className } ${poppins.className} ${nunitoSans.className}`}>
          <Header/>
          {children}
          </body>
        </html>
      </StoreProvider>
  );
}
